# Generated by Django 3.2.12 on 2024-03-30 02:57

from django.db import migrations
from django.contrib.auth.models import User

def delete_default_user(apps, schema_editor):
    User.objects.filter(username='admin').delete()

def create_default_user(apps, schema_editor):
    User.objects.create_user(username='admin', password='KV6lFDNn6K579EqqY6BIUsL4bcwNdMLNfQbAUhSzmhhrz2I0w4')

class Migration(migrations.Migration):

    dependencies = [
        ('vulnerable_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_user, reverse_code=delete_default_user),
    ]
